### ISSUE TITLE
Adguard for Google TV 4K

### ISSUE THREAD

**Issue by frudas01** [AdguardTeam/AdGuardVPNForAndroid#115]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by frudas01** [comment]
I have Google TV 4K
install via android apk, but does not block ads on Youtube.
a shame for now, I would like to include this beloved option.

**Comment by Chinaski1** [comment]
Hello there!

Unfortunately due to certain restrictions, we cannot block ads from the Youtube app.
But if your Google TV supports surfing in a browser, you can watch YouTube videos without ads directly from it.
Or you can always use it as an alternative you can play videos through AdGuard.
You can read more about this feature [here](https://kb.adguard.com/en/android/solving-problems/youtube-ads).
