### ISSUE TITLE
Compatibility Ads and Vpn not open filtered sites

### ISSUE THREAD

**Issue by desperanish** [AdguardTeam/AdGuardVPNForAndroid#156]
When i use both all things are good and show me this work.
But when i go to chrome can't open filtered websites in compatibility mode.

This is my device diagnoses:

```
Tokens
VPN token: 07a9f9ce-0f75-4a71-8678-1aadb4d3087b
Credentials: 
  auth token: g3h1p99811ayu2i4
  expiration time: 25.07.3283 10:14:32
  expiration time, sec: 41452065872
  license status: VALID

Device
username: 07a9f9ce-0f75-4a71-8678-1aadb4d3087b
applicationId: a584b5f4095c108b

Current endpoint
id: Z2JfbG9uZG9u
country: بریتانیا
city: لندن
premium only: false
ping bonus: 0
domain name: m9009-gb-lhr-01-98p9k2xs.adguard.io
connected IP address: /81.92.200.74:443

Connection status
protocol: Socks5
data received: ۳٫۶۵ کیلوبایت
data sent: ۵٫۲۵ کیلوبایت
estimate RTT: 37409 ms
estimate packet loss: ۰٫۰۰%
protocol: http2

```

Please consider it
Thanks

**Comment by Chinaski1** [comment]
Hello there!

Sorry for the late reply.
Could you give us a little more detail?

- What kind of error does the chrome browser show? 
- Do all sites stop opening?
- The Internet connection is stable in other applications?

**Comment by Birbber** [comment]
@desperanish Any news?

**Comment by desperanish** [comment]
Sites are censored then show page can't load.
Other not filtered sites are open
Sites and apps if be filtered not load and if they open work.
Means Adguard+AdguardVPN do nothing for me. Open sites are open and filtered sites are filter.
Adguard separately work good and AdguardVPN separately work good too.
But together not work.

**Comment by infinitewaveparticle** [comment]
@desperanish Please explain your issue in your native language so the developers can translate it with a translation application.

**Comment by Birbber** [comment]
@desperanish
To troubleshoot this issue, we need to get additional logs from both applications.

For AdGuard adblocker app:
1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;

For AdGuard VPN application:
1. Go to `App settings` --> `Advanced settings` --> `Logging level` --> `Extended`
2. Reproduce the issue and remember the exact time it happened
3. Go to `Support` --> `Export logs and system info`

Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Birbber** [comment]
@desperanish We've fixed the compatibility issue in the latest AdGuard VPN beta version and will release production version soon. Please wait for the release and check if the issue still reproducible.

**Comment by maxikuzmin** [comment]
@desperanish could you tell if the problem was solved?

**Comment by maxikuzmin** [comment]
The issue has been closed due to no reply
