### ISSUE TITLE
AG drop AG VPN connection when tap on notification.

### ISSUE THREAD

**Issue by Globulopolis** [AdguardTeam/AdGuardVPNForAndroid#160]
### Issue Details

- **AdGuard version:**
  - 3.6.7(41)
- **AdGuard VPN version:**
  - 2.0.154
- **VPN mode:**
  - Local VPN
- **Device:**
  - Samsung  Galaxy S9+
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Working AG VPN.

### Actual Behavior

AG drop AG VPN connection when tap on notification.

### Steps to reproduce

- Open AG go to settings, tap on AdGuard VPN.
- Tap on 'Connect', wait until connect.
- Open notification area and tap on AdGuard notification text.

**Comment by Birbber** [comment]
@Globulopolis Hi! To troubleshoot this issue, we need to get additional logs from both applications.

For AdGuard adblocker app:
1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;

For AdGuard VPN application:
1. Go to `App settings` --> `Advanced settings` --> `Logging level` --> `Extended`
2. Reproduce the issue and remember the exact time it happened
3. Go to `Support` --> `Export logs and system info`

Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Birbber** [comment]
Thanks, the logs have been received. Will transfer it to our devs.

**Comment by Globulopolis** [comment]
> Hi! Re-check the issue on the latest beta version please, it should be already fixed.

Seems no issue with latest version. Thanks.
