### ISSUE TITLE
The "add new network" button does not update when switching to another wifi in Auto-protect wifi 

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdGuardVPNForAndroid#190]
Auto-protect wifi does not update the "add new network" button when switching to another wifi, it does not appear.
After exiting/entering or disabling/enabling the function, the button to add another network appears

**Comment by aliafshany** [comment]
please see this video @maxikuzmin, I am commenting here because i thought it is related.
i am changing my connection from LTE to WiFi
unfortunately, adguard cannot detect the new network and it remains like that.
can you do something anout it to connect automatically?
i tried auto protection but it didn't work.

https://user-images.githubusercontent.com/40741745/186647121-c7f07216-a341-4c0e-9670-16fd873fbec5.mp4
