### ISSUE TITLE
Locations not found in AdGuard VPN

### ISSUE THREAD

**Issue by chatch314** [AdguardTeam/AdGuardVPNForAndroid#243]
On VodafoneUK adguard vpn claims no location found. Any ideas how to solve?
![Screenshot_20230106_080837_AdGuard VPN](https://user-images.githubusercontent.com/110598669/210960688-25890fcd-d724-4bdd-a496-381e5d67ee62.jpg)
![Screenshot_20230106_080844_AdGuard VPN](https://user-images.githubusercontent.com/110598669/210961022-e61d6b6a-0c7f-4383-b74c-070b2dae80d7.jpg)

```
Tokens
VPN token: updating...
Credentials: 
  auth token: updating...
  expiration time: updating...
  expiration time, sec: updating...
  license status: updating...

Device
username: —
applicationId: —

Current endpoint
id: —
country: —
city: —
premium only: —
ping bonus: —
domain name: —
connected IP address: —

Connection status
transport mode: Socks5
last connection at: 05.01.2023 21:40:01
data received: 301 kB
data sent: 1.74 MB
estimate RTT: —
estimate packet loss: —
protocol: —

```

**Comment by maxikuzmin** [comment]
@chatch314 to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@chatch314 any news?

**Comment by maxikuzmin** [comment]
@chatch314 did you change the mode and the problem went away?

**Comment by chatch314** [comment]
Yes, I changed in the Android settings which is the always on VPN.  Must be AdGuard, not AdGuard VPN then the problem went away.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
