### ISSUE TITLE
Enabling "Block connections without VPN" In AdGuard for Android's VPN mode while using AdGuard VPN's intergration mode causes the internet not to work.

### ISSUE THREAD

**Issue by kah0922** [AdguardTeam/AdGuardVPNForAndroid#25]
- **AdGuard VPN version:**
  - 1.0.155
- **VPN mode:**
  - AdGuard for Android Intergration
- **Device:**
  -  Essential Phone PH-1
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Expected Behavior

Selecting "Block connections without VPN" in on AdGuard for Android's VPN mode while using AdGuard VPN in Integration mode should still have the internet work.

### Actual Behavior

Selecting "Block connections without VPN" on the AdGuard for Android App while using Integration mode causes the internet to not work.

### Additional Information

"Block connections without VPN" is commonly used as a VPN Killswitch.

**Comment by ameshkov** [comment]
We simply won't be able to resolve this.

1. Android thinks that AdGuard is a VPN app, so the traffic of all apps that aren't routed through AG is blocked.
2. If we route AdGuard VPN traffic through AdGuard, there will be an infinite loop because AG itself routes traffic through AG VPN app.

The only solution would be to fully integrate VPN **inside** the AdGuard app. We might do this in the future, but not too soon.
