### ISSUE TITLE
IPv4/IPv6 Mixed Mode Latency

### ISSUE THREAD

**Issue by Nemisor** [AdguardTeam/AdGuardVPNForAndroid#366]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.4 beta 2(21)

### Operating mode

VPN

### Environment

```markdown
- OS: Android 14
- Device: Pixel 7
- Firmware: MP1.0
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Leave IPv4/IPv6 enabled
2. Run Speedtest 
3. Ping times average 260+

### Expected Behavior

Switching to only IPv4 results in ping times around 10-14 on average. This is consistent across several devices and between several servers.

### Screenshots

<details><summary>Screenshot 1:</summary>

**Comment by Nemisor** [comment]
![Screenshot_20230926-175650](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/1268315/f126ba1c-b9ea-4fcb-94ec-2345a3c471a2)
![Screenshot_20230926-175906](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/1268315/c44ceb99-420d-43e6-9ab5-933e265792b7)
Here are the test results with IPv4/IPv6 enabled vs just IPv4. Notice also the massively improved upload speeds. This happens on both wifi and cellular.

**Comment by Batman2814** [comment]
This problem is with more than just AdGuard VPN for Android. It also happens with AdGuard VPN for Windows. I reported this to AdGuard over a year ago, showing screenshots of speed tests not working correctly on Windows when VPN is enabled, where the Ping was High, and download and upload tests were low. So, AdGuard, you should be able to fix this with all the data I sent you in the past to fix this in all AdGuard VPN products. So, for now, I will disable IPv6 until it's fixed.

**Comment by ESurina** [comment]
@Nemisor I remind you
