### ISSUE TITLE
AdGuard VPN on Andriod consume high battery during my sleep period even not connect VPN.

### ISSUE THREAD

**Issue by nik2ads** [AdguardTeam/AdGuardVPNForAndroid#391]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.6.25

### Operating mode

VPN

### Environment

```markdown
- OS: Android 13
- Device: POCO F3
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to Android setting
2. Select 'Battery'
3. Select ' AdGuardVPN'

### Screenshots

![95383](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/132831857/530c5c4e-d602-470c-b619-2c051b6a89ec)

**Comment by DevSergio02** [comment]
This bug has been reported on Reddit (https://www.reddit.com/r/Adguard/comments/17vid44/sudden_and_seemingly_temporary_drain_issue_with/), and I even reported it myself to the Adguard developers a few weeks ago. Apparently, the bug is that the application has an endless loop to check the integration mode with Adguard. This does not happen in the previous version of Adguard.

**Comment by flo-m** [comment]
i can confirm the issue... heavy battery drain even while not connected.
Reported this two times. Support told me that they are aware of this and have created an issue on github, but linked this to an adguard app instead vpn problem...

Hello!
 
As we mentioned in our previous message, we're aware of that issue and going to fix it in future updates.
 
Also, we've created the [GitHub issue](https://github.com/AdguardTeam/AdguardForAndroid/issues/4960) for this problem. So if the issue is still relevant for you, please report it as a comment in this issue. This way, you'll be able to communicate directly with our developers.
 
Best,
AdGuard Support 💚

**Comment by maxikuzmin** [comment]
@nik2ads @DevSergio02 @flo-m thanks! Unfortunately this problem is now being observed for both AdGuard and AdGuard VPN, but for some reason not on all devices. We are indeed aware of this issue and are trying to figure out the cause. It will take us some more time to resolve this issue. 
Please continue to monitor the power consumption on your devices. Whenever you see a recurrence of high power consumption, please send us the logs, it will be very helpful.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Extended

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 391 number in the subject
specify the exact time when the issue occurred

**Comment by maxikuzmin** [comment]
@nik2ads @DevSergio02 @flo-m The unusual thing about this consumption is also that the compatibility mode block has not changed in any way since AdGuard VPN version 2.3. 
Have you observed this behavior before? Or did it only start with version 2.6?

**Comment by nik2ads** [comment]
> @nik2ads @DevSergio02 @flo-m thanks! Unfortunately this problem is now being observed for both AdGuard and AdGuard VPN, but for some reason not on all devices. We are indeed aware of this issue and are trying to figure out the cause. It will take us some more time to resolve this issue. Please continue to monitor the power consumption on your devices. Whenever you see a recurrence of high power consumption, please send us the logs, it will be very helpful.
> 
> * Enable debug logging:
> 
> Settings -> General -> Advanced -> Logging level -> Extended
> 
> * Reproduce the issue related to the button behaviour, then remember the exact time when it happened
> * Collect logs:
> 
> Settings -> General -> Advanced -> Export logs and system info
> 
> * Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
> 
> mention the 391 number in the subject specify the exact time when the issue occurred

I can't collect logging in debug mode for you. Because AdGuard VPN was crash during 'Export logs and system info' process. My symptoms occur during my sleep time. So, the log size might be huge.

**Comment by Iamz** [comment]
> @nik2ads @DevSergio02 @flo-m thanks! Unfortunately this problem is now being observed for both AdGuard and AdGuard VPN, but for some reason not on all devices. We are indeed aware of this issue and are trying to figure out the cause. It will take us some more time to resolve this issue. Please continue to monitor the power consumption on your devices. Whenever you see a recurrence of high power consumption, please send us the logs, it will be very helpful.
> 
> * Enable debug logging:
> 
> Settings -> General -> Advanced -> Logging level -> Extended
> 
> * Reproduce the issue related to the button behaviour, then remember the exact time when it happened
> * Collect logs:
> 
> Settings -> General -> Advanced -> Export logs and system info
> 
> * Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
> 
> mention the 391 number in the subject specify the exact time when the issue occurred

I believe I can consistently reproduce the issue on my Z Fold 5 running Android 14. I have collected and sent the logs to the email address.

**Comment by maxikuzmin** [comment]
@Iamz thanks! We'll look into your logs

**Comment by flo-m** [comment]
in my case, all previous version do also consume battery (even tough much less than 2.6).
From 2.6, there is a wakelock held by:
com.adguard.vpn/androidx.work.impl.background.systemjob.SystemJobService
This one is not present in e.g. 2.5
See held active in gsam (adguard vpn is holding the device active 2h of 8h):
![Screenshot_2023-12-13-06-16-20-024_com gsamlabs bbm](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/3896428/f5153d6e-02ed-4833-ac8d-7edf07b6cd1d)

See Process details:
![Uploading Screenshot_2023-12-13-06-14-02-956_com.gsamlabs.bbm.png…]()

**Comment by maxikuzmin** [comment]
@nik2ads @DevSergio02 @flo-m we found what the problem is. It will be fixed in an upcoming update. Thank you very much for your information!

**Comment by maxikuzmin** [comment]
@nik2ads @DevSergio02 @flo-m please test this in AdGuard VPN 2.7 Beta 1 released today or wait for the release version tomorrow, please let us know the results

**Comment by Nietsnut** [comment]
Yes, no battery drain in 2.7 beta. Adguard VPN is usable again 👍🏻

**Comment by flo-m** [comment]
yes, can also confirm: it works fine now !

**Comment by DevSergio02** [comment]
I'm testing with 2.7 Beta 1 and so far I still notice that it constantly runs in the background and starts consuming battery power again, just like version 2.6 did. I will try to install the 2.7 stable version, which is now available and report back if it keeps happening.

**Comment by maxikuzmin** [comment]
@DevSergio02 okay, we're waiting for feedback

**Comment by flo-m** [comment]
I can confirm that the issue ist still present in Version 2.7.8, while IT was fixed in 2.7 Beta. 

Can someone else also confirm?

**Comment by DevSergio02** [comment]
> I can confirm that the issue ist still present in Version 2.7.8, while IT was fixed in 2.7 Beta.
> 
> Can someone else also confirm? Update: 2.7.6 (which seems to be 2.7 beta 1) is working fine. 2.7.8 (which is the new stable) has the same old issue with wakelock.

I have had the same wakelock even in version 2.7 Beta 1, in One UI's Device Care, it marks that the app is constantly in the background doing "something", something that in version 2.5 is usually never in the background, or sometimes it appears but for a very short time.

**Comment by DevSergio02** [comment]
> @DevSergio02 okay, we're waiting for feedback

Unfortunately, the problem still occurs in the stable version of Adguard VPN 2.7. I have just sent the logs with the new version to the Adguard email you indicated above. 

What I have been able to observe in the logs is that a kind of "refresh" of network parameters is constantly repeated because supposedly the "link properties has changed": 

```
14:43:17.661 [pool-5-thread-1] DEBUG com.adguard.vpnclient.VpnCore - Link properties changed
14:43:17.662 [pool-5-thread-1] DEBUG com.adguard.vpnclient.VpnCoreUtils - Refreshing network parameters
```

I don't know if this has to do with the Adguard integration mode or not.

**Comment by maxikuzmin** [comment]
@DevSergio02 @flo-m we looking into the problem. Have you also updated AdGuard to the latest version 4.3.1?

**Comment by DevSergio02** [comment]
> @DevSergio02 @flo-m we looking into the problem. Have you also updated AdGuard to the latest version 4.3.1?

Yes, I have done the tests with Adguard 4.3.1.

**Comment by Emtp563** [comment]
No change for me. Excessive battery usage. Adguard 4.3.1/VPN 2.7.8

**Comment by flo-m** [comment]
i have to admit that the both beta + stable 2.7 is having the same issue (wakelock) after some time...

**Comment by Nietsnut** [comment]
Yes,  at first it seemed resolved, but the problem returned

**Comment by rak-rak** [comment]
Hi,  found this by searching. I just want to confirm the issue on two devices:
Samsung S22+ / Tab S9 (both Android 14 stock)
Adguard 4.3.1 and Adguard VPN 2.7.8

High battery consumption of Adguard VPN while not using it.

**Comment by maxikuzmin** [comment]
@rak-rak @Nietsnut @flo-m @Emtp563 @DevSergio02 we are looking into this, thanks for the info. If there are any new logs, please send them in

**Comment by enakr** [comment]
+ CRM 854336

**Comment by flo-m** [comment]
the newly release beta 2.8.12 still has the same wakelock issue...

**Comment by maxikuzmin** [comment]
@flo-m we're still looking into the issue

**Comment by DevSergio02** [comment]
Is there any news on when you are going to fix the problem? I (as well as many others) are stuck on version 2.5, and at some point it will stop working due to some "major" change that requires a higher version to use Adguard VPN 😢😢

**Comment by maxikuzmin** [comment]
@DevSergio02 we are trying to resolve the issue, I apologize for the long wait. I hope that in the next update we will be able to resolve this issue

**Comment by tkhquang** [comment]
Any updates on this? I have a S23 Ultra and Adguard VPN never let my phone go to deep sleep. Please fix this, I had no other choice but to uninstall Adguard VPN for now.

**Comment by maxikuzmin** [comment]
@tkhquang in the process of being resolved. Tentatively planned to be solved by the next 2.8 update

**Comment by dnw3039** [comment]
I am using AdGuard VPN v2.8 Nightly 1      this is still a problem , on a Google Pixel 5, Android 14

**Comment by DevSergio02** [comment]
I see that the problem has been marked as fixed... is there an Adguard VPN build coming soon that contains the new changes???

**Comment by rak-rak** [comment]
Same question. Nothing changed until now, no update. Issue persists.

**Comment by flo-m** [comment]
Yeah its unbelievable that adguard team is not willing to fix this issue asap...

**Comment by ameshkov** [comment]
The issue will be gone in the next beta version, we apologize for it taking too long to publish.

**Comment by Emtp563** [comment]
How about you send me a private beta .APK?

**Comment by ameshkov** [comment]
@Emtp563 you can check the nightly version instead, follow the instruction here:
https://adguard-vpn.com/en/beta.html?platform=android&release=nightly

**Comment by rak-rak** [comment]
@ameshkov And what about users like us who paid for subscription and expect regular versions?

The first time I wrote here was January 4th. Three months ago.

Adguard VPN drain >10% of my battery.

Sorry, but I'm not happy anymore about this.

**Comment by ameshkov** [comment]
@rak-rak it took us much longer than anticipated to troubleshoot and figure out what's causing this. At this point we have to push it as a part of a regular update and not a fix. The problem is that the fix is built on top of many changes in v2.8 update. If we decide to push it "as is" there's a great risk of introducing new bugs.

The temporary solution for everyone affected right now is to upgrade to a nightly version (or wait a few days until the beta is out). But I'd suggest to do it only temporarily and switch back to stable once it's out.

Again, I apologize for the whole situtation, we should've prioritized it differently and spend more time on troubleshooting exactly when it was reported and not a month later.

**Comment by rak-rak** [comment]
Thanks for reply. We waited for 3 months now. Hopefully we will get an update soon.

**Comment by DevSergio02** [comment]
I've been running Adguard 2.8 Nightly 2 (the latest beta version from the Play Store) for a few days now, and so far the bug has completely disappeared.

**Comment by rak-rak** [comment]
@DevSergio02 Play Store still shows v2.7.25 for me. Registered as beta user.

And you got a nightly version from play store?

**Comment by artemiv4nov** [comment]
@DevSergio02 please send 1 day debug logs to our devteam@adguard.com

**Comment by dnw3039** [comment]
I have recently done a factory reset on my Pixel 5 phone and the and the sleep problem has gone away. The device has 64% deep sleep over 9 days. Previously it was about 5%. Battery function is much better. So it may not have been an Adguard problem.

**Comment by DevSergio02** [comment]
> I have recently done a factory reset on my Pixel 5 phone and the and the sleep problem has gone away. The device has 64% deep sleep over 9 days. Previously it was about 5%. Battery function is much better. So it may not have been an Adguard problem.

In Adguard 2.8 Beta 1???

**Comment by dnw3039** [comment]
Yes, AdGuard VPN v2.8 Beta 1.

**Comment by GreenJeans** [comment]
I can confirm the bug seems to be back.  A few days ago the issue seemed to have been resolved, but today I noticed extremely high battery drain overnight to find Adguard VPN with extremely high wakelock usage.  App info reports version 2.8.79.

**Comment by GreenJeans** [comment]
@DevSergio02 logs emailed

**Comment by ghost** [comment]
@artemiv4nov The stable version of Adguard VPN 2.8 has just been released. Have you checked that the bug no longer occurs in this version, as it did in Beta 1? I will still try this version to confirm whether the bug has disappeared or not.

**Comment by ghost** [comment]
> @artemiv4nov The stable version of Adguard VPN 2.8 has just been released. Have you checked that the bug no longer occurs in this version, as it did in Beta 1? I will still try this version to confirm whether the bug has disappeared or not.

Update: the stable version of Adguard 2.8 still has exactly the same problem as Beta 1, it still drains battery. The bug had been fixed in Nightly 2 as I had explained before, but it is back. 

I'm very sorry but seeing that this bug has been going on for 6 months and it doesn't seem to change much, I'm uninstalling Adguard VPN from my phone until this bug is fixed. It's a bit frustrating to see how you pay for a VPN client and they don't fix a bug as important as this one, which significantly affects the battery life of our phones. 

I will leave the phone for 1 hour draining the battery in idle and I will send the extended logs of Adguard VPN, but I will uninstall the application until this problem is solved.

**Comment by artemiv4nov** [comment]
@DevSergio02 Hi! Are you sure you just use a release version, not a beta version? In the release version, everything should be okay. Also, the fix has already been sent to Nightly track, you can check there.

**Comment by ghost** [comment]
> @DevSergio02 Hi! Are you sure you just use a release version, not a beta version? In the release version, everything should be okay. Also, the fix has already been sent to Nightly track, you can check there.

Hello again! I just checked today, and apparently the stable version of Adguard VPN no longer drains battery. Yesterday when I installed it I saw that it started to increase consumption a bit, but I reinstalled the app and it hasn't drained again since. 

For my part, the problem is now solved (and I'm very happy about it) 😄

**Comment by GreenJeans** [comment]
@DevSergio02 @artemiv4nov After testing for 24hrs the issue appears resolved for me in v2.8.1 Nightly 4 as well! Thank you to the dev team for finally tackling this issue.

**Comment by TPS** [comment]
@AdguardTeam Before this is closed & so forgotten, any chance for _this_ to be implemented?:

> We _really_ could use the Battery usage page that's [available in AGa](https://adguard.com/kb/adguard-for-android/solving-problems/battery/) in AGVPNa, too.
> 
> ![Official example](<https://cdn.adtidy.org/content/articles/battery/1.png>)

**Comment by artemiv4nov** [comment]
@DevSergio02 glad to know that:)

@TPS not yet planned. But you could open a new task, let's see how many user will upvote this.

**Comment by TPS** [comment]
> @TPS not yet planned. But you could open a new task, let's see how many user will upvote this.

@artemiv4nov I posted [the RFE for the Battery Usage page](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/391#issuecomment-2066997304) @ https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/454.

**Comment by mahara** [comment]
The app in Google Play Store doesn't seem to updated to the latest version yet: 2.8.x; it's still showing 2.7.25.

When it will be updated to the latest version?

**Comment by Versty** [comment]
@mahara The 2.8.1 version will be available very soon!
