### ISSUE TITLE
AdGuard VPN do not connecting to servers

### ISSUE THREAD

**Issue by kebox7** [AdguardTeam/AdGuardVPNForAndroid#489]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

AdGuard VPN for Android (v2.10) does not connect to servers, but AdGuard VPN for Windows (v2.4.0 1475) works fine. Both devices are connected to the network via WiFi through the same access point.

**Comment by Versty** [comment]
@kebox7 Hi! 
Please force stop the application in system settings and then try to connect again.

**Comment by kebox7** [comment]
Hi, @Versty!

That's what I did. I closed the app itself, and also killed the background process.  Yesterday I couldn't connect all day, and today the problem went away by itself.  Not the first time, but eventually the connection was established. Although, as I wrote above, the desktop version connects instantly.

**Comment by Versty** [comment]
@kebox7 Looks like it was caused by the application cache. 
If this problem occurs on your device next time, please create a new issue, enable debug logging in both Android and Windows apps, restart both apps, and try to connect. Then collect logs and send it to `qa@adguard.com` email with `[android]` tag in the subject, mention the reproduction time in the description.
