### ISSUE TITLE
AdGuard VPN connection drops when Android phone enter sleep/doze mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardVPNForAndroid#63]
@EntropySmoke commented on [Tue Dec 22 2020](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/44)

Title of this topic is misleading. The connection doesn't actually drop, but some devices bypass VPN tunnels in Sleep Mode.
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
- **AdGuard VPN version:**
0.7.1
- **VPN mode:**
AdGuard VPN in VPN Mode
- **Operating system and version:**
Android 10/11 (not rooted)
- **Other network-level software:**
AdGuard Home DNS server

### Expected Behavior
The expectation is that Android devices use AdGuard VPN when in Sleep Mode for all situations if "Always-On" and "Block Connections Without VPN" are enabled in Android Network & Internet settings. 

### Actual Behavior
Local DNS resolver logs show that Android Sleep Mode WiFi activity includes Android devices attempting to resolve Google domains, such as google.com, connectivitycheck.gstatic.com, and play.googleapis.com outside of AdGuard VPN tunnels using WiFi-assigned DNS resolver address instead of VPN-set resolver address. The same devices do use VPN tunnels in Sleep Mode when receiving email and other internet data. That means that VPN tunnel connection persists and isn't dropped in Sleep Mode. 

### Additional Information
It is almost as if there is a forced Android-set VPN Split Tunneling that can't be configured in any VPN apps. The same behavior happens with all VPN apps and protocols, but not on all devices. Disabling or enabling Battery Optimization for VPN apps makes no difference.

Some say that Captive Portal check is the issue, but none of following ADB Shell Captive Portal commands resolve this issue for me:
settings put global captive_portal_detection_enabled 0
settings put global captive_portal_server localhost
settings put global captive_portal_mode 0
settings put global wifi_watchdog_on 0
settings put global wifi_watchdog_background_check_enabled 0
pm disable com.android.captiveportallogin

This behavior is similar to how Android devices use carrier/SIM-card WiFi calling that also bypasses installed VPN apps and exclusively uses IPSec 3GPP ePDG tunnels to make/receive calls and/or SMS/MMS. Only app-based WiFi calling (WhatsApp, Viber, Skype, Telegram, Signal, etc.) and other internet apps can use installed VPN app tunnels.

There is definitely no way to tunnel carrier/SIM-card WiFi calling through installed VPN apps, but **is there a way to prevent Android devices in Sleep Mode from trying to connect to google.com, connectivitycheck.gstatic.com, and play.googleapis.com outside of VPN tunnels?** Connecting to those Google domains outside of VPN defeats the point of using a VPN!

**Comment by infinitewaveparticle** [comment]
Two comments:

1. I actually do notice AdGuard VPN disconnecting quite often while I'm not using my devices no matter if I'm using WiFi or mobile data (using it in conjunction with the regular AdGuard app). I disable battery optimization wherever possible, but it's still an issue on the devices I leave connected to the internet while not in use. In order of most-often disconnected to least-often disconnected my devices are:
a) Samsung Galaxy J3 running stock Android 7
b) NVIDIA Shield running stock Android 9 (Android TV)
c) Samsung Galaxy S7 Edge running stock Android 8
Sometimes the problem gets even worse and will disconnect fairly quickly after reconnecting (or sometimes it won't reconnect at all). In my experience the only ways I've been able to fix this when it happens is to switch from manual SOCKS5 to Compatibility Mode or to switch from Compatibility Mode to manual SOCKS5 mode. If this fails I need to put my device into airplane mode, force stop both apps, clear their caches, reopen and enable them, and then reconnect to the internet.

Something I've just found out (which is surprising and hopefully helpful to you) is that if I switch the logging level for AdGuard VPN to Extended it very rarely disconnects. In fact I don't recall it disconnecting even once since I've done that. The only problems with this is that it makes collecting logs for the issue impossible and also takes up a lot of disk space and battery usage.

2. I know it's not a "fix" for your exact issue stated above, but if you disable the offending apps from connecting when the screen is off would that temporarily help? Unless of course you're talking about mtalk.google.com which would defeat notifications for people using that service. I'm glad I do not.

**Comment by artemiv4nov** [comment]
Well, we have to investigate the problem deeply. On this-next week, We will come back with the investigation results.

**Comment by nshekhovtsov** [comment]
Is there any option to send us logs from your Local DNS resolver?
I am trying to reproduce your issue. I see, that there is some connects to the google addresses. It is okey, because lots of apps are able to make internet queries.
But, I cannot identify which connect goes through VPN tunnel, which otherwise.

**Comment by nshekhovtsov** [comment]
@infinitewaveparticle Is there any option to send us logs?
Which version of AdGuard VPN do you use?
Is there any specific settings installed?

**Comment by nshekhovtsov** [comment]
We researched that the Android System makes bootstrap requests through VPN tunnel via private DNS ignoring the Kill Switch. That's why you was able to see gstatic.com requests. Also there is some system requests which goes outside the VPN tunnel, ignoring any setting as Kill switch.

Google don't advise to use private DNS setting with VPN. The issue on the tracker: https://issuetracker.google.com/issues/141674015. 

Try to enable AdGuard Home DNS in the AdGuard VPN settings, and disable private DNS.
