### ISSUE TITLE
Can't use the Costa app with Adguard VPN on and using a different location.

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardVPNForAndroid#76]
### Prerequisites

- [✓ ] I am running the latest version
- [✓ ] I checked the documentation and found no answer
- [✓ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - V1.1(10)
- **VPN mode:**
  - Comparability mode with Adguard
- **Device:**
  - Google Pixel 5
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior

When you open the app a error message appears at the bottom of the screen with AdguardVPN on. 

### Actual Behavior

I have Adguard VPN on and set to the Netherlands (which had the best ping and speed) when I try to open the Costa app it says "To use the Costa app you must be located in Scotland, England or Wales." Turning off the VPN fixes the issue as well as setting the location to United Kingdom.

### Screenshots

![Screenshot_20210224-090257.png](https://user-images.githubusercontent.com/72349391/108978751-dc12a400-7681-11eb-981f-fc63ea06b932.png)

### Additional Information

The error message cannot be seen by taking a screenshot.

**Comment by anastenko** [comment]
Hello.
This is a normal behavior of Costa App.
"To use the Costa app you must be located in Scotland, England or Wales." message indicates that you can't access this application from any other location, but the ones mentioned. So once you choose "Netherlands" as a location you are not able to use Costa app.
AdGuard VPN performs its function: it changes the location and your application doesn't work since you have a different location

**Comment by anastenko** [comment]
Anyway, in case you still want to keep this location while using the Costa app, you can try to exclude this application from filtering:
Go to Apps management (it will redirect you to AdGuard app) -> click the application -> disable AdGuard protection for this app
